name: Publish to MCP Registry

on:
  workflow_run:
    workflows: ["Release Test"]
    types:
      - completed

jobs:
  publish-mcp:
    runs-on: ubuntu-latest
    # Only run if the test workflow succeeded
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: read
      id-token: write # Required for OIDC authentication

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Validate server.json schema
        run: |
          # Download MCP server schema
          curl -o server.schema.json https://static.modelcontextprotocol.io/schemas/2025-09-29/server.schema.json
          
          # Validate server.json against schema using Node.js
          node -e "
            const Ajv = require('ajv');
            const fs = require('fs');
            const ajv = new Ajv({allErrors: true, verbose: true});
            const schema = JSON.parse(fs.readFileSync('server.schema.json', 'utf8'));
            const data = JSON.parse(fs.readFileSync('server.json', 'utf8'));
            const validate = ajv.compile(schema);
            const valid = validate(data);
            if (!valid) {
              console.log('Validation errors:', validate.errors);
              process.exit(1);
            } else {
              console.log('✅ server.json is valid!');
            }
          "

      - name: Install MCP Publisher
        run: |
          curl -L "https://github.com/modelcontextprotocol/registry/releases/download/v1.1.0/mcp-publisher_1.1.0_$(uname -s | tr '[:upper:]' '[:lower:]')_$(uname -m | sed 's/x86_64/amd64/;s/aarch64/arm64/').tar.gz" | tar xz mcp-publisher
          chmod +x mcp-publisher
          sudo mv mcp-publisher /usr/local/bin/

      - name: Login to MCP Registry
        run: mcp-publisher login github-oidc

      - name: Publish to MCP Registry
        run: mcp-publisher publish

      - name: Upload MCP logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mcp-publish-logs
          path: |
            ~/.mcp-publisher/logs/*.log
          retention-days: 7
